export const CaptionList = [
  {
    id: "1",
    content:
      "Introducing Skipli AI - the faster, smarter way to craft compelling content. Experiencing all the magic of AI-driven writing assistant and get great results with fewer headache.",
    tag: "#AI #ContentMarketing #Content",
  },
  {
    id: "2",
    content:
      "Introducing Skipli AI - the faster, smarter way to craft compelling content. Experiencing all the magic of AI-driven writing assistant and get great results with fewer headache.",
    tag: "#AI #ContentMarketing #Content",
  },
];

export const captionToneList = [
  { id: "1", value: "friendly", label: "Friendly" },
  { id: "2", value: "luxury", label: "Luxury" },
  { id: "3", value: "relaxed", label: "Relaxed" },
  { id: "4", value: "relaxed", label: "Relaxed" },
  { id: "5", value: "professional", label: "Professional" },
  { id: "6", value: "bold", label: "Bold" },
  { id: "7", value: "adventurous", label: "Adventurous" },
  { id: "8", value: "witty", label: "Witty" },
  { id: "9", value: "persuasive", label: "Persuasive" },
  { id: "10", value: "empathetic", label: "Empathetic" },
];

export const inspireIdeaList = [
  { id: "1", label: "Idea generated by AI 1" },
  { id: "2", label: "Idea generated by AI 2" },
  { id: "3", label: "Idea generated by AI 3" },
  { id: "4", label: "Idea generated by AI 4" },
  { id: "5", label: "Idea generated by AI 5" },
  { id: "6", label: "Idea generated by AI 6" },
  { id: "7", label: "Idea generated by AI 7" },
  { id: "8", label: "Idea generated by AI 8" },
  { id: "9", label: "Idea generated by AI 9" },
  { id: "10", label: "Idea generated by AI 10" },
];
