import React from "react";
import "./index.scss";
import ContentCard from "../../Components/Content";

export default function ProfilePage() {
  const listA = [
    {
      id: "1",
      content:
        "Introducing Skipli AI - the faster, smarter way to craft compelling content. Experiencing all the magic of AI-driven writing assistant and get great results with fewer headache.",
      tag: "#AI #ContentMarketing #Content",
    },
    {
      id: "2",
      content:
        "Introducing Skipli AI - the faster, smarter way to craft compelling content. Experiencing all the magic of AI-driven writing assistant and get great results with fewer headache.",
      tag: "#AI #ContentMarketing #Content",
    },
  ];
  const listB = [
    {
      id: "1",
      content:
        "Introducing Skipli AI - the faster, smarter way to craft compelling content. Experiencing all the magic of AI-driven writing assistant and get great results with fewer headache.",
      tag: "#AI #ContentMarketing #Content",
    },
    {
      id: "2",
      content:
        "Introducing Skipli AI - the faster, smarter way to craft compelling content. Experiencing all the magic of AI-driven writing assistant and get great results with fewer headache.",
      tag: "#AI #ContentMarketing #Content",
    },
  ];
  return (
    <div className="profile-page">
      <h2>Saved Content</h2>
      <h3>Skipli is launching SkipliAI</h3>
      <div className="content-ai">
        {listA.map((item, idx) => (
          <ContentCard key={idx} content={item.content} tag={item.tag} />
        ))}
      </div>
      <h3>Idea is generated by AI2</h3>
      <div className="content-ai">
        {listB.map((item, idx) => (
          <ContentCard key={idx} content={item.content} tag={item.tag} />
        ))}
      </div>
    </div>
  );
}
